import type { Metadata } from "next"
import { Montserrat } from "next/font/google"
import "@/styles/tailwind.css"

const fontSans = Montserrat({ subsets: ["latin"], variable: "--font-sans" })
const fontHeading = Montserrat({
  subsets: ["latin"],
  variable: "--font-heading",
})

export const metadata: Metadata = {
  title: "Next Starter",
  description: "Generated by create next app",
}

export type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={` font-sans text-slate-900 antialiased ${fontSans.variable} ${fontHeading.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
